# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/JavaScript"
    schedule:
      interval: "daily"
      time: "13:40"
      timezone: "Asia/Bangkok"
    open-pull-requests-limit: 10
