(def num1 10)
(def num2 5)
(def str1 "Hello")
(def str2 "hello")
(def lst1 [1 2 3])
(def lst2 [1 2 3])

(println "Number compare")
(println "10 = 5 is " (= num1 num2))
(println "10 < 5 is " (< num1 num2))
(println "10 > 5 is " (> num1 num2))
(println "10 <= 5 is " (<= num1 num2))
(println "10 >= 5 is " (>= num1 num2))
(println "10 != 5 is " (not= num1 num2))
(println "\n")

(println "String compare")
(println "Hello = hello is " (= str1 str2))
(println "Hello != hello is " (not= str1 str2))
(println "\n")

(println "####### Vector compare")
(println "[1 2 3] = [1 2 3] is "(= lst1 lst2))
(println "list1 and lis2 is identical objects? "(identical? lst1 lst2)) 
(println "\n")

(println "Instance compare")
(println "Hello is string instance? "(instance? String str1))
(println "10 is number instance?"(instance? Number num1)) 
(println "10 is string instance?"(instance? String num1)) 
(println "\n")
