repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/realm/SwiftLint
    rev: 0.50.3
    hooks:
      - id: swiftlint

  # - repo: https://github.com/cpp-linter/cpp-linter-hooks
  #   rev: v0.2.1
  #   hooks:
  #     - id: clang-format
  #       args: [--style=file] # to load .clang-format
  #     - id: clang-tidy
  #       args: [--checks=.clang-tidy] # path/to/.clang-tidy
