repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/realm/SwiftLint
    rev: 0.50.3
    hooks:
      - id: swiftlint

  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: v0.2.1
    hooks:
      - id: clang-format

  - repo: https://github.com/vincentjames501/pre-commit-clojure
    rev: v2.0.3
    hooks:
      - id: clj-kondo
        args: ["error"]
        stages: [merge-commit, push, manual]
        always_run: true

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
        files: ^/Go/
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
        files: ^/Go/
