name: Clojure CI

on:
  push:
    branches:
      - main

jobs:
  clojure:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: ./your-repo-name

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: "zulu"

      - name: Install Clojure CLI on macOS
        run: |
          brew install clojure/tools/clojure
        if: runner.os == 'macOS-latest'

      - name: Install Clojure CLI on Linux
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
          chmod +x linux-install-1.10.1.536.sh
          sudo ./linux-install-1.10.1.536.sh
        if: runner.os == 'ubuntu-latest'

      - name: Install Leiningen
        run: |
          mkdir -p $HOME/bin
          curl -o $HOME/bin/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x $HOME/bin/lein

      - name: Install Babashka
        run: |
          curl -o bb -L https://github.com/babashka/babashka/releases/download/v0.7.8/babashka-0.7.8
          chmod +x bb
          sudo mv bb /usr/local/bin

      - name: Cache clojure dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.edn
          key: cljdeps-${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
          restore-keys: cljdeps-${{ runner.os }}-

      - name: Run Boot
        run: |
          if [[ "${runner.os}" == "ubuntu-latest" || "${runner.os}" == "macOS-latest" ]]; then
            # Download and install Boot Wrapper
            curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
            chmod +x boot
            ./boot -V
          fi
        shell: bash
