name: clojure-linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clj-kondo:
    name: runner / clj-kondo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2

      - name: Change working directory to /Java/
        run: cd Java

      - name: clj-kondo
        uses: nnichols/clojure-lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
