name: cpp-linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Change working directory to /C++
        run: cd C++

      - name: Install C++ (g++) and clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-11 clang-format
        shell: bash

      - name: Run clang-format
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.h" -o -name "*.cxx" \) -not -path "./build/*" -exec clang-format -i {} \;

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
