name: C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change working directory to C++
        run: |
          (cd C++)
        working-directory: ${{ github.workspace }}

      - name: Print current working directory
        run: pwd

      - name: Build project
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          submodule_update: ON
          run_tests: ON
          unit_test_build: -Dtest=ON
