name: C++ CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Set up CMake
        run: |
          mkdir build
          cd build
          cmake ..
        working-directory: C++

      - name: Build project
        run: |
          cmake --build build
        working-directory: C++

      - name: Test project
        run: |
          cd build
          ctest
        working-directory: C++
