name: Go CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Change working directory to Go
        run: cd Go

      - name: Print current working directory
        run: pwd

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.15"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
