name: java-lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Change working directory to /Java/
        run: cd Java

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          checkstyle_config: sun_checks.xml
