name: JavaScript CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
        working-directory: JavaScript/

      - name: Build (if present)
        run: npm run build --if-present
        working-directory: JavaScript/

      - name: Run tests
        run: npm test
        working-directory: JavaScript/
