name: JavaScript CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clear npm cache
        run: npm cache clean -f
        working-directory: JavaScript/

      - name: Remove node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm package-lock.json
        working-directory: JavaScript/

      - name: Remove fsevents from package.json
        run: |
          npm uninstall fsevents
          npm prune
        working-directory: JavaScript/

      - name: Generate package-lock.json
        run: npm install
        working-directory: JavaScript/

      - name: Use specific npm version
        run: npm install -g npm@9.5.1
        working-directory: JavaScript/

      - name: Build (if present)
        run: npm run build --if-present
        working-directory: JavaScript/

      - name: Run tests
        run: npm test
        working-directory: JavaScript/

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: JavaScript/node_modules
          key: npm-${{ hashFiles('JavaScript/package-lock.json') }}
