name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build-wrapper
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          mkdir -p bw-output
          chmod +x build-wrapper-linux-x86/build-wrapper-linux-x86-64

      - name: Clean Build Directory
        run: rm -rf C++/build1/

      - name: Create Build Directory
        run: mkdir -p C++/build1/

      - name: Configure and Build
        run: |
          cd C++/build1/
          cmake ..
          make

      - name: Verify compile_commands.json existence
        run: |
          find C++/build1/ -name compile_commands.json -exec echo "File found: {}" \;

      - name: Copy compile_commands.json
        run: |
          find C++/build1/ -name compile_commands.json -exec cp {} . \;

      - name: Verify build-wrapper-dump.json existence
        run: |
          find $GITHUB_WORKSPACE -name build-wrapper-dump.json -exec echo "File found: {}" \;

      - name: Copy build-wrapper-dump.json
        run: |
          find $GITHUB_WORKSPACE -name build-wrapper-dump.json -exec cp {} bw-output/ \;

      - name: List Build Directory
        run: ls C++/build1/

      - name: List bw-output Directory
        run: ls bw-output/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=tealerr_fundamental-programming
            -Dsonar.organization=tealerr
            -Dsonar.sources=C++
            -Dsonar.cfamily.build-wrapper-output=bw-output
            -Dsonar.exclusions=**/*.java

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
