name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build-wrapper
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          mv build-wrapper-linux-x86/* C++/build/
          chmod +x C++/build/build-wrapper-linux-x86-64

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
          sudo apt-get install -y cmake

      - name: Configure
        run: cd C++/ && cmake -B C++/build -S .

      - name: Build
        run: cd C++/build/ && /usr/bin/cmake --build .

      - name: Run build-wrapper
        run: C++/build/build-wrapper-linux-x86-64 --out-dir C++ /usr/bin/cmake --build C++/build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.exclusions=**/*.java
            -Dsonar.c.file.suffixes=-
            -Dsonar.cpp.file.suffixes=-
            -Dsonar.objc.file.suffixes=-
