name: SonarQube Scan

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  sonarqube:
    runs-on:
      - self-hosted
      - label-1

    services:
      ngrok:
        image: wernight/ngrok
        ports:
          - 4040:4040
          - 9000:9000

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "17"

      - name: Run SonarQube Scan
        run: mvn sonar:sonar -Dsonar.host.url=https://2c3a-2405-9800-bc92-71bc-d953-fabf-3a6c-f87b.ngrok-free.app/ -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Stop Ngrok
        run: pkill ngrok
