name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build-wrapper
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          mkdir -p C++/build1/
          mv build-wrapper-linux-x86/* C++/build1/
          chmod +x C++/build1/build-wrapper-linux-x86-64

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
          sudo apt-get install -y cmake

      - name: Configure C++ project
        run: cd C++/build1 && cmake ..

      - name: Build C++ project
        run: cd C++/build1 && cmake --build .

      - name: Run build-wrapper for C++
        run: C++/build1/build-wrapper-linux-x86-64 --out-dir C++/bw-output /usr/bin/cmake --build C++/build1

      - name: Setup SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=tealerr_fundamental-programming
            -Dsonar.projectName=tealerr_fundamental-programming
            -Dsonar.projectVersion=1.0
            -Dsonar.sources=C++
            -Dsonar.cfamily.build-wrapper-output=C++/bw-output
