name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build-wrapper
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          mkdir -p C++/build1/
          mv build-wrapper-linux-x86/* C++/build1/
          chmod +x C++/build1/build-wrapper-linux-x86-64

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
          sudo apt-get install -y cmake

      - name: Configure
        run: |
          cd C++/build1/
          cmake ..

      - name: Verify CMakeCache.txt
        run: ls C++/build1/CMakeCache.txt

      - name: Create Output Directory
        run: mkdir -p $HOME/bw-output

      - name: Run build-wrapper
        run: C++/build1/build-wrapper-linux-x86-64 --out-dir bw-output /usr/bin/cmake --build C++/build1

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=tealerr_fundamental-programming
            -Dsonar.organization=tealerr
            -Dsonar.sources=C++
            -Dsonar.cfamily.build-wrapper-output=bw-output
            -Dsonar.exclusions=**/*.java

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
