name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install SonarQube plugins (SonarClojure)
        run: |
          sudo mkdir -p /opt/sonarqube/extensions/plugins/

          wget https://github.com/fsantiag/sonar-clojure/archive/refs/tags/v2.2.0.zip
          unzip v2.2.0.zip -d /opt/sonarqube/extensions/plugins/

          mv /opt/sonarqube/extensions/plugins/sonar-clojure-2.2.0 /opt/sonarqube/extensions/plugins/sonar-clojure-plugin

          if systemctl list-unit-files | grep -q sonarqube.service; then
            sudo systemctl restart sonarqube
          else
            echo "SonarQube service not found. Please restart the service manually."
          fi

      - name: Build Clojure project
        run: lein uberjar
        working-directory: Clojure

      - name: Run SonarCloud analysis
        run: sonar-scanner
          -Dsonar.projectKey=tealerr_fundamental-programming
          -Dsonar.organization=tealerr
          -Dsonar.projectName=fundamental-programming
          -Dsonar.projectVersion=1.0
          -Dsonar.sources=.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
