name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install build-wrapper
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip
          mv build-wrapper-linux-x86/* C++/build/
          chmod +x C++/build/build-wrapper-linux-x86-64

      # - name: list files in build-wrapper-linux-x86-64
      #   run: |
      #     ls -l build-wrapper
      #     ls -l build-wrapper/build-wrapper-linux-x86

      - name: Configure CMake
        run: cmake -B C++/build -S C++/.

      - name: Run build-wrapper
        run: |
          ./C++/build/build-wrapper-linux-x86-64 --out-dir C++ cmake build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.exclusions=**/*.java
            -Dsonar.c.file.suffixes=-
            -Dsonar.cpp.file.suffixes=-
            -Dsonar.objc.file.suffixes=-

              C++/build/CMakeCache.txt
