name: Swift CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
